language: csharp
os:
  - osx
  - linux

# Ubuntu 14.04
sudo: required
dist: bionic

# OS X 10.12
osx_image: xcode11.2

mono:
  - 4.4.2

dotnet: 3.0.100

before_install:
  - git fetch --unshallow # Travis always does a shallow clone, but GitVersion needs the full history including branches and tags
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git fetch origin

script:
  - ./build.sh --target=Test